# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["Proyectomcd/core.py"]

doc_url = "https://Danielfernandez18.github.io/Proyectomcd/"

git_url = "https://github.com/Danielfernandezv18/proyecto.git"

def custom_doc_links(name): return None
